
/*******       GLOBAL       *******/

export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const DISMISS_ALERT = "DISMISS_ALERT";

// IS LOAD
export const SET_ADMINISTRATORS_IS_LOAD = "SET_ADMINISTRATORS_IS_LOAD";
export const SET_FEEDBACKS_IS_LOAD = "SET_FEEDBACKS_IS_LOAD";
export const SET_MANAGERS_IS_LOAD = "SET_MANAGERS_IS_LOAD";
export const SET_FITNESS_CENTERS_IS_LOAD = "SET_FITNESS_CENTERS_IS_LOAD";
export const SET_MODULES_IS_LOAD = "SET_MODULES_IS_LOAD";

// IS NOT LOAD
export const SET_ADMINISTRATORS_IS_NOT_LOAD = "SET_ADMINISTRATORS_IS_NOT_LOAD";
export const SET_FEEDBACKS_IS_NOT_LOAD = "SET_FEEDBACKS_IS_NOT_LOAD";
export const SET_MANAGERS_IS_NOT_LOAD = "SET_MANAGERS_IS_NOT_LOAD";
export const SET_FITNESS_CENTERS_IS_NOT_LOAD = "SET_FITNESS_CENTERS_IS_NOT_LOAD";
export const SET_MODULES_IS_NOT_LOAD = "SET_MODULES_IS_NOT_LOAD";


/*******       MANAGERS       *******/

export const SET_MANAGERS = "SET_MANAGERS";
export const SET_INITIAL_MANAGERS = "SET_INITIAL_MANAGERS";
export const SET_MANAGER_ACTIVITY = "SET_MANAGER_ACTIVITY";
export const SET_VALIDATE_MANAGER = "SET_VALIDATE_MANAGER";

export const DISPLAY_MANAGERS_UPDATE_CONFIRM = "DISPLAY_MANAGERS_UPDATE_CONFIRM";
export const DISMISS_MANAGERS_UPDATE_CONFIRM = "DISMISS_MANAGERS_UPDATE_CONFIRM";

export const DISPLAY_MANAGERS_DETAILS_MODAL = "DISPLAY_MANAGERS_DETAILS_MODAL";
export const DISMISS_MANAGERS_DETAILS_MODAL = "DISMISS_MANAGERS_DETAILS_MODAL";

export const SET_FITNESS_CENTERS = "SET_FITNESS_CENTERS";

export const SET_MANAGERS_FILTER_NAME = "SET_MANAGERS_FILTER_NAME";
export const SET_MANAGERS_FILTER_SELECT_FITNESS_CENTER = "SET_MANAGERS_FILTER_SELECT_FITNESS_CENTER";

export const MANAGERS_RESET_FILTER = "MANAGERS_RESET_FILTER";

/*******       ADMINISTRATORS       *******/

export const SET_ADMINISTRATORS = "SET_ADMINISTRATORS";
export const SET_INITIAL_ADMINISTRATORS = "SET_INITIAL_ADMINISTRATORS";

export const SET_ADMINISTRATORS_FILTER_NAME = "SET_ADMINISTRATORS_FILTER_NAME";

export const SET_ADMINISTRATOR = "SET_ADMINISTRATOR";
export const ADD_ADMINISTRATOR = "ADD_ADMINISTRATOR";
export const RESET_CURRENT_ADMINISTRATOR = "RESET_CURRENT_ADMINISTRATOR";
export const SET_CURRENT_ADMINISTRATOR_FIRST_NAME = "SET_CURRENT_ADMINISTRATOR_FIRST_NAME";
export const SET_CURRENT_ADMINISTRATOR_LAST_NAME = "SET_CURRENT_ADMINISTRATOR_LAST_NAME";
export const SET_CURRENT_ADMINISTRATOR_EMAIL = "SET_CURRENT_ADMINISTRATOR_EMAIL";
export const SET_CURRENT_ADMINISTRATOR_PHONE = "SET_CURRENT_ADMINISTRATOR_PHONE";
export const SET_CURRENT_ADMINISTRATOR_PASSWORD = "SET_CURRENT_ADMINISTRATOR_PASSWORD";
export const SET_CURRENT_ADMINISTRATOR_PASSWORD_CONFIRM = "SET_CURRENT_ADMINISTRATOR_PASSWORD_CONFIRM";

export const DISPLAY_EDIT_USER_MODAL = "DISPLAY_EDIT_USER_MODAL";
export const DISPLAY_CREATE_USER_MODAL = "DISPLAY_CREATE_USER_MODAL";
export const DISMISS_EDIT_USER_MODAL = "DISMISS_EDIT_USER_MODAL";

export const DISPLAY_DELETE_USER_MODAL = "DISPLAY_DELETE_USER_MODAL";
export const DISMISS_DELETE_USER_MODAL = "DISMISS_DELETE_USER_MODAL";