
/*******       GLOBAL       *******/

export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const DISMISS_ALERT = "DISMISS_ALERT";

// IS LOAD
export const SET_ADMINISTRATORS_IS_LOAD = "SET_ADMINISTRATORS_IS_LOAD";
export const SET_FEEDBACKS_IS_LOAD = "SET_FEEDBACKS_IS_LOAD";
export const SET_MANAGERS_IS_LOAD = "SET_MANAGERS_IS_LOAD";
export const SET_MODULES_IS_LOAD = "SET_MODULES_IS_LOAD";

// IS NOT LOAD
export const SET_ADMINISTRATORS_IS_NOT_LOAD = "SET_ADMINISTRATORS_IS_NOT_LOAD";
export const SET_FEEDBACKS_IS_NOT_LOAD = "SET_FEEDBACKS_IS_NOT_LOAD";
export const SET_MANAGERS_IS_NOT_LOAD = "SET_MANAGERS_IS_NOT_LOAD";
export const SET_MODULES_IS_NOT_LOAD = "SET_MODULES_IS_NOT_LOAD";


/*******       ADMINISTRATORS       *******/

export const SET_ADMINISTRATORS = "SET_ADMINISTRATORS";
export const SET_INITIAL_ADMINISTRATORS = "SET_INITIAL_ADMINISTRATORS";

export const SET_ADMINISTRATORS_FILTER_NAME = "SET_ADMINISTRATORS_FILTER_NAME";

export const DISPLAY_DELETE_USER_MODAL = "DISPLAY_DELETE_USER_MODAL";
export const DISMISS_DELETE_USER_MODAL = "DISMISS_DELETE_USER_MODAL";