
/*******       GLOBAL       *******/

export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const DISMISS_ALERT = "DISMISS_ALERT";

// IS LOAD
export const SET_ADMINISTRATORS_IS_LOAD = "SET_ADMINISTRATORS_IS_LOAD";
export const SET_USERS_FEEDBACKS_IS_LOAD = "SET_USERS_FEEDBACKS_IS_LOAD";
export const SET_MANAGERS_FEEDBACKS_IS_LOAD = "SET_MANAGERS_FEEDBACKS_IS_LOAD";
export const SET_MANAGERS_IS_LOAD = "SET_MANAGERS_IS_LOAD";
export const SET_USERS_IS_LOAD = "SET_USERS_IS_LOAD";
export const SET_FITNESS_CENTERS_IS_LOAD = "SET_FITNESS_CENTERS_IS_LOAD";
export const SET_MODULES_IS_LOAD = "SET_MODULES_IS_LOAD";
export const SET_MODULE_STATES_IS_LOAD = "SET_MODULE_STATES_IS_LOAD";

// IS NOT LOAD
export const SET_ADMINISTRATORS_IS_NOT_LOAD = "SET_ADMINISTRATORS_IS_NOT_LOAD";
export const SET_USERS_FEEDBACKS_IS_NOT_LOAD = "SET_USERS_FEEDBACKS_IS_NOT_LOAD";
export const SET_MANAGERS_FEEDBACKS_IS_NOT_LOAD = "SET_MANAGERS_FEEDBACKS_IS_NOT_LOAD";
export const SET_MANAGERS_IS_NOT_LOAD = "SET_MANAGERS_IS_NOT_LOAD";
export const SET_USERS_IS_NOT_LOAD = "SET_USERS_IS_NOT_LOAD";
export const SET_FITNESS_CENTERS_IS_NOT_LOAD = "SET_FITNESS_CENTERS_IS_NOT_LOAD";
export const SET_MODULES_IS_NOT_LOAD = "SET_MODULES_IS_NOT_LOAD";
export const SET_MODULE_STATES_IS_NOT_LOAD = "SET_MODULE_STATES_IS_NOT_LOAD";

/*******       USERS       *******/

export const SET_USERS = "SET_USERS";
export const SET_INITIAL_USERS = "SET_INITIAL_USERS";

export const SET_USERS_FILTER_NAME = "SET_USERS_FILTER_NAME";
export const SET_USERS_FILTER_SELECT_FITNESS_CENTER = "SET_USERS_FILTER_SELECT_FITNESS_CENTER";
export const USERS_RESET_FILTER = "USERS_RESET_FILTER";

/*******       MANAGERS       *******/

export const SET_MANAGERS = "SET_MANAGERS";
export const SET_INITIAL_MANAGERS = "SET_INITIAL_MANAGERS";
export const SET_MANAGER_ACTIVITY = "SET_MANAGER_ACTIVITY";
export const SET_VALIDATE_MANAGER = "SET_VALIDATE_MANAGER";
export const SET_UNDO_REFUSE_MANAGER = "SET_UNDO_REFUSE_MANAGER";

export const DISPLAY_CONSULT_SIRET_MODAL = "DISPLAY_CONSULT_SIRET_MODAL";
export const DISMISS_CONSULT_SIRET_MODAL = "DISMISS_CONSULT_SIRET_MODAL";

export const DISPLAY_MANAGERS_UPDATE_CONFIRM = "DISPLAY_MANAGERS_UPDATE_CONFIRM";
export const DISMISS_MANAGERS_UPDATE_CONFIRM = "DISMISS_MANAGERS_UPDATE_CONFIRM";

export const DISPLAY_MANAGERS_DETAILS_MODAL = "DISPLAY_MANAGERS_DETAILS_MODAL";
export const DISMISS_MANAGERS_DETAILS_MODAL = "DISMISS_MANAGERS_DETAILS_MODAL";

export const SET_FITNESS_CENTERS = "SET_FITNESS_CENTERS";

export const SET_MANAGERS_FILTER_NAME = "SET_MANAGERS_FILTER_NAME";
export const SET_MANAGERS_FILTER_SELECT_FITNESS_CENTER = "SET_MANAGERS_FILTER_SELECT_FITNESS_CENTER";

export const MANAGERS_RESET_FILTER = "MANAGERS_RESET_FILTER";

/*******       ADMINISTRATORS       *******/

export const SET_ADMINISTRATORS = "SET_ADMINISTRATORS";
export const SET_INITIAL_ADMINISTRATORS = "SET_INITIAL_ADMINISTRATORS";

export const SET_ADMINISTRATORS_FILTER_NAME = "SET_ADMINISTRATORS_FILTER_NAME";

export const SET_ADMINISTRATOR = "SET_ADMINISTRATOR";
export const ADD_ADMINISTRATOR = "ADD_ADMINISTRATOR";
export const RESET_CURRENT_ADMINISTRATOR = "RESET_CURRENT_ADMINISTRATOR";
export const SET_CURRENT_ADMINISTRATOR_FIRST_NAME = "SET_CURRENT_ADMINISTRATOR_FIRST_NAME";
export const SET_CURRENT_ADMINISTRATOR_LAST_NAME = "SET_CURRENT_ADMINISTRATOR_LAST_NAME";
export const SET_CURRENT_ADMINISTRATOR_EMAIL = "SET_CURRENT_ADMINISTRATOR_EMAIL";
export const SET_CURRENT_ADMINISTRATOR_PHONE = "SET_CURRENT_ADMINISTRATOR_PHONE";
export const SET_CURRENT_ADMINISTRATOR_PASSWORD = "SET_CURRENT_ADMINISTRATOR_PASSWORD";
export const SET_CURRENT_ADMINISTRATOR_PASSWORD_CONFIRM = "SET_CURRENT_ADMINISTRATOR_PASSWORD_CONFIRM";

export const DISPLAY_EDIT_USER_MODAL = "DISPLAY_EDIT_USER_MODAL";
export const DISPLAY_CREATE_USER_MODAL = "DISPLAY_CREATE_USER_MODAL";
export const DISMISS_EDIT_USER_MODAL = "DISMISS_EDIT_USER_MODAL";

export const DISPLAY_DELETE_USER_MODAL = "DISPLAY_DELETE_USER_MODAL";
export const DISMISS_DELETE_USER_MODAL = "DISMISS_DELETE_USER_MODAL";

/*******       MODULES       *******/

export const SET_MODULES = "SET_MODULES";
export const SET_INITIAL_MODULES = "SET_INITIAL_MODULES";

export const ADD_MODULE = "ADD_MODULE";
export const UPDATE_MODULE = "UPDATE_MODULE";

export const SET_MODULE_STATES = "SET_MODULE_STATES";

export const SET_MODULES_FILTER_UUID = "SET_MODULES_FILTER_UUID";
export const SET_MODULES_FILTER_SELECT_FITNESS_CENTER = "SET_MODULES_FILTER_SELECT_FITNESS_CENTER";
export const MODULES_RESET_FILTER = "MODULES_RESET_FILTER";

export const DISPLAY_EDIT_MODULE_MODAL = "DISPLAY_EDIT_MODULE_MODAL";
export const DISPLAY_CREATE_MODULE_MODAL = "DISPLAY_CREATE_MODULE_MODAL";
export const DISMISS_EDIT_MODULE_MODAL = "DISMISS_EDIT_MODULE_MODAL";

export const SET_CURRENT_MODULE_AUTO_GENERATE_UUID = "SET_CURRENT_MODULE_AUTO_GENERATE_UUID";
export const SET_CURRENT_MODULE_UUID = "SET_CURRENT_MODULE_UUID";
export const SET_CURRENT_MODULE_FITNESS_CENTER_ID = "SET_CURRENT_MODULE_FITNESS_CENTER_ID";
export const SET_CURRENT_MODULE_MACHINE_TYPE = "SET_CURRENT_MODULE_MACHINE_TYPE";
export const SET_CURRENT_MODULE_MODULE_STATE_ID = "SET_CURRENT_MODULE_MODULE_STATE_ID";

/*******       FEEDBACKS       *******/
export const SET_MANAGERS_FEEDBACKS = "SET_MANAGERS_FEEDBACKS";
export const DISPLAY_FEEDBACK = "DISPLAY_FEEDBACK";
export const DISMISS_FEEDBACK = "DISMISS_FEEDBACK";
export const SET_USERS_FEEDBACKS = "SET_USERS_FEEDBACKS";
